#define FLOW_TAP_TERM 100
#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "4Wrzm/EeKMqb"
#define LAYER_STATE_16BIT

#define RGB_MATRIX_STARTUP_SPD 60

